title: try-learning-lab
description: try learning lab
template:
  repo: try-learning-lab-template
  name: try-learning-lab
before:
  - type: createIssue
    title: Getting Started with USGS Data Science Pipelines
    body: 00-pipelines-overview.md
steps:
  - title: Get the big picture
    description: Learn about our goals and general approaches for data analysis pipelines
    event: issues.assigned
    link: '{{ repoUrl }}/issues/1'
  - title: Why use a pipeline?
    description: The makers of the drake R package have a good answer to this question.
    video: 'https://player.vimeo.com/video/362383350'
    event: issues.closed
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: closeIssue
  - title: Decomposition into functions
    description: With our tools you always define steps as functions. Try it here.
    event: issues.closed
  - title: The anatomy of a makefile YAML
    description: Our pipelines use YAML to describe dependencies.
    event: issues.closed
