title: Intro to Data Analysis Pipelines
description: Intro to Data Analysis Pipelines for USGS Data Science
template:
  repo: ds-pipelines-1-template
  name: ds-pipelines-1
before:
  - type: createIssue
    title: Get started with USGS Data Science pipelines
    body: 00-overview.md
    store:
      first_issue_url: '{{ result.data.html_url }}'
steps:
  - title: Get the big picture
    description: Learn about our goals and general approaches for data analysis pipelines
    link: '{{ store.first_issue_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 00-configure.md
        store:
          configure_comment_url: '{{ result.data.html_url }}'
  - title: Configure your R environment
    description: >-
      Install packages and establish an RStudio project for the exercises in
      course
    link: '{{ store.configure_comment_url }}'
    event: issues.closed
    actions:
      - type: createIssue
        title: Structure your code predictably
        body: 01-structure.md
        store:
          structure_issue_url: '{{ result.data.html_url }}'
  - title: Directory structure and phases
    description: Team conventions for how our pipelines are organized
    event: issues.assigned
    link: '{{ store.structure_issue_url }}'
    actions:
      - type: createIssue
        title: Where to learn more
        body: 90-references.md
