title: try-learning-lab
description: try learning lab
template:
  repo: try-learning-lab-template
  name: try-learning-lab
before:
  - type: createIssue
    title: Get started with USGS Data Science pipelines
    body: 00-overview.md
    store:
      first_issue_url: '{{ result.data.html_url }}'
steps:
  - title: Get the big picture
    description: Learn about our goals and general approaches for data analysis pipelines
    link: '{{ store.first_issue_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 00-configure.md
        store:
          configure_comment_url: '{{ result.data.html_url }}'
  - title: Configure your R environment
    description: Install packages and establish an RStudio project for the exercises in course
    link: '{{ store.configure_comment_url }}'
    event: issues.closed
    actions:
      - type: createIssue
        title: Structure your code predictably
        body: 01-structure.md
        store:
          structure_issue_url: '{{ result.data.html_url }}'

# 20 Directory structure and phases
  - title: Directory structure and phases
    description: Team conventions for how our pipelines are organized
    event: issues.assigned
    link: '{{ store.structure_issue_url }}'
    actions:
      - type: respond
        with: 20-phases-overview.md
        store:
          phases_comment_url: '{{ result.data.html_url }}'
  - title: Open a pull request for directory structure
    description: Open a pull request.
    event: pull_request.opened
    link: '{{ store.structure_issue_url }}'
    actions:
      - type: closeIssue
        issue: Welcome
        action_id: prev
        required: false
      - type: createPullRequestComment
        body: 21-phases-activity.md
        file: Readme.md
        position: 1
        data:
          welcomeLink: "%actions.prev.data.html_url%"

# 90 appendix
  - title: Organize your projects
    description: Learn to organize into functions, targets, and phases
    event: issues.closed
    actions:
      - type: createIssue
        title: Where to learn more
        body: 90-references.md
